// For Login
export const LOGIN_INITIATED = 'LOGIN_INITIATED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const CHECKING_AUTHORIZATION = 'CHECKING_AUTHORIZATION';
export const AUTHORIZED = 'AUTHORIZED';
export const UNAUTHORIZED = 'UNAUTHORIZED';
export const LOGGEDOUT = 'LOGGEDOUT';

// For SignUp
export const SIGNUP_INITIATED = 'SIGNUP_INITIATED';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const SIGNUP_DONE = 'SIGNUP_DONE';
